name: Hello World

on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Echo Hello World
      run: echo "Hello World"

    - name: Show existing workflows
      run: |
        ls ./.github/workflows/

    - name: test this world
      uses: ./.github/workflows/Test.yaml