name: Hello World

on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Echo Hello World
      run: echo "Hello World"

    - name: test this world
      #run: |
      #  ls ./.github/workflows/
      uses: ./.github/workflows/Test.yaml