name: Upgrade AKS Cluster

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 2 * * 6'

#env:
#  CLUSTER_RESOURCE_GROUP: 
#  CLUSTER_NAME: 

jobs:
  read-file:
    permissions:
      id-token: write
      contents: read
      actions: read
    runs-on: ubuntu-latest
    #environment: testk8
    steps:
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install cifs-utils
      run: sudo apt-get install cifs-utils

    - name: Mount file share
      run: |
        mkdir -p /home/runner/fileshare
        sudo mount -t cifs //azcopytest20250116.file.core.windows.net/githublearning /home/runner/fileshare -o username=${{ secrets.FS_USERNAME }},password=${{ secrets.FS_PASSWORD }}

    - name: Read value from file
      id: read_file
      run: |
        FILE_CONTENT=$(cat /home/runner/fileshare/approval.txt)
        echo "::set-output name=file_content::$FILE_CONTENT"

    - name: Use the value
      run: echo "The value from the file is ${{ steps.read_file.outputs.file_content }}"

  edit-file:
    permissions:
      id-token: write
      contents: write
      actions: write
    runs-on: ubuntu-latest
    environment: testk8
    steps:
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install cifs-utils
      run: sudo apt-get install cifs-utils

    - name: Mount file share
      run: |
        mkdir -p /home/runner/fileshare
        sudo mount -t cifs //azcopytest20250116.file.core.windows.net/githublearning /home/runner/fileshare -o username=${{ secrets.FS_USERNAME }},password=${{ secrets.FS_PASSWORD }}

    - name: Write value to file
      run: |
        echo "Approved" > /home/runner/fileshare/approval.txt

    - name: List files in file share
      run: ls /home/runner/fileshare