name: Upgrade AKS Cluster

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 2 * * 6'

#env:
#  CLUSTER_RESOURCE_GROUP: 
#  CLUSTER_NAME: 

jobs:
  upgrade-aks-cluster:
    permissions:
      id-token: write
      contents: read
      actions: read
    runs-on: ubuntu-latest
    #environment: testk8
    steps:
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show